# Generated by Django 5.1.2 on 2024-10-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('title', models.CharField(help_text='Уникальное название категории, не более 256 символов', max_length=256, verbose_name='Название')),
                ('output_order', models.PositiveSmallIntegerField(default=1000, help_text='Целое число, чем меньше, тем выше в выборке', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_on_main', models.BooleanField(default=False, verbose_name='На главную')),
                ('title', models.CharField(help_text='Уникальное название пиццы, не более 256 символов', max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('structure', models.TextField(verbose_name='Состав')),
                ('size', models.PositiveSmallIntegerField(default=30, help_text='Целое число, по умолчанию 30', verbose_name='Размер, см.')),
                ('output_order', models.PositiveSmallIntegerField(default=1000, help_text='Целое число, чем меньше, тем выше в выборке', verbose_name='Порядок отображения')),
                ('price', models.DecimalField(decimal_places=2, help_text='Десятичная дробь(2 знака после запятой), не более 20 знаков', max_digits=20, verbose_name='Цена, руб.')),
                ('category', models.ManyToManyField(related_name='pizza', to='pizza.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
                'ordering': ('output_order', 'title'),
            },
        ),
    ]
