# Generated by Django 5.1.2 on 2024-10-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default=0, upload_to='pizza', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
